### ISSUE TITLE
Unable to use Warp+

### ISSUE THREAD

**Issue by hutchy50** [maple3142/cf-warp#17]
After following the instructions and even doing a reinstall https://www.cloudflare.com/cdn-cgi/trace is still saying warp=on instead of warp=plus. As far as I can see from the data.json it should be enabled and cf-warp says that I have warp+ quota.

If I'm missing something or have done something wrong any help would be appreciated.

**Comment by maple3142** [comment]
It isn't guaranteened to be able to use it. Maybe Cloudflare had terminated this.

**Comment by Dondrejohnson5** [comment]
I've been able to obtain warp+ usage thanks to [this repo](https://github.com/ViRb3/wgcf). Trick is though, I link the same account key to both profiles I made using this repo and the other repo above. Use the wireguard profile from the latter on devices, and use the former to continue to obtain more quota (unless you paid for unlimited then just use the WireGuard profile of the repo above and link the key).
