### ISSUE TITLE
Getting error when faking referrers

### ISSUE THREAD

**Issue by ronnie1102** [maple3142/cf-warp#19]
Getting this error again

cf-warp 10
Prepare faking Warp+ referrer for 10 times.
(node:4392) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token e in JSON at position 0
at JSON.parse ()
at module.exports (C:\Users\ronni\AppData\Roaming\npm\node_modules\cf-warp\lib\register.js:29:14)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async module.exports (C:\Users\ronni\AppData\Roaming\npm\node_modules\cf-warp\lib\ref.js:4:2)
at async C:\Users\ronni\AppData\Roaming\npm\node_modules\cf-warp\cli.js:83:4
(node:4392) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4392) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by maple3142** [comment]
Duplicated, #7
