### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by hamiltonrn** [maple3142/cf-warp#2]
**Installed cf-warp through yarn:**
success Installed "cf-warp@1.1.1" with binaries:
      - cf-warp
Done in 0.74s.

**But when I try to run cf-warp, I receive a _command not found_ error.**

PS: I'm running Manjaro Linux (Arch).

**Comment by maple3142** [comment]
Maybe Yarn's global dir is not in your `PATH`, so running `export PATH="$PATH:$(yarn global bin)"` is needed.
You can also add that line to `.bashrc` and source it.

**Comment by hamiltonrn** [comment]
Thank you, it worked! 

Em 28/10/2019 08:28, maple escreveu:

> Maybe Yarn's global dir is not in your PATH, so running export PATH="$PATH:$(yarn global bin)" is needed.
> You can also add that line to .bashrc and source it. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/maple3142/cf-warp/issues/2?email_source=notifications&amp;email_token=ANJPDFUBGLFT6CRFN23SU7DQQ3SJJA5CNFSM4JFYPBOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECM3VKY#issuecomment-546945707
[2]
