### ISSUE TITLE
Using Warp config on WireGuard without 0.0.0.0/0 IP

### ISSUE THREAD

**Issue by Dondrejohnson5** [maple3142/cf-warp#28]
I use WireGuard on Android, and I imported the Warp config, and it works well. But certain apps and websites say I am using a private proxy, and I find that the problem lies within the `Allowed IPs`being `0.0.0.0/0`. The problem is, `0.0.0.0/0` is what allows me to watch YouTube videos with no buffer, any other IP address I tried can't come even close. What can I try to modify to increase receive and transmit speed almost the same way only `0.0.0.0/0`can, and at the same time satisfy sites that don't work well with private IPs? The Cloudflare app (when 1.1.1.1, NOT Warp, is enabled) seems to be able to do it.

**Comment by maple3142** [comment]
I don't know what do you mean by "using a private proxy"

**Comment by Dondrejohnson5** [comment]
> I don't know what do you mean by "using a private proxy"

![Screenshot_20210801-130113](https://user-images.githubusercontent.com/29732079/127779323-756efd8c-9c8d-4410-ac89-defb5ee18a04.png)

**Comment by maple3142** [comment]
The 0.0.0.0/0 ip is not the ip that websites will see. Website only sees CloudFlare's ip, and the could make a list of CloudFlare Warp ips and block users like this. It is not something that this project can fix, as it has to do with CloudFlare and those websites.
