### ISSUE TITLE
i cant install cf-warp

### ISSUE THREAD

**Issue by Boy656** [maple3142/cf-warp#30]
![Screenshot_20211129-175657](https://user-images.githubusercontent.com/69907104/143890917-5d5a37cd-eaf5-446d-88e0-d0edb8db125d.jpg)
I want to install cf-warp using yarn 
yarn global add cf-warp
But I can't, I took a picture that shows the problem

**Comment by maple3142** [comment]
I don't know, it seems to be a problem with termux. It is recommended to install it on a computer.
