### ISSUE TITLE
HTTPError: Too Many Requests

### ISSUE THREAD

**Issue by okeehou** [maple3142/cf-warp#7]
I got this error everytime. I need to change it to "2" and can't run too frequently.

```
cf-warp 10
Prepare faking Warp+ referrer for 10 times.
#1 fake referrer finished
#2 fake referrer finished
(node:680) UnhandledPromiseRejectionWarning: HTTPError: Too Many Requests
    at responseErrorThrower (/snapshot/cf-warp/node_modules/xfetch-js/xfetch.js:37:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /snapshot/cf-warp/lib/register.js:11:15
    at async /snapshot/cf-warp/lib/ref.js:4:2
    at async /snapshot/cf-warp/cli.js:64:4
(node:680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:680) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by anakaiti** [comment]
Should be fixed by #5

**Comment by ronnie1102** [comment]
Getting this error again

cf-warp 10
Prepare faking Warp+ referrer for 10 times.
(node:4392) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token e in JSON at position 0
    at JSON.parse (<anonymous>)
    at module.exports (C:\Users\ronni\AppData\Roaming\npm\node_modules\cf-warp\lib\register.js:29:14)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async module.exports (C:\Users\ronni\AppData\Roaming\npm\node_modules\cf-warp\lib\ref.js:4:2)
    at async C:\Users\ronni\AppData\Roaming\npm\node_modules\cf-warp\cli.js:83:4
(node:4392) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4392) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by JediJoker** [comment]
Also getting this error running from NPM package on OpenWRT.

**Comment by maple3142** [comment]
This can't really be fixed, because it is imposed by Cloudflare side. Just retry with a smaller number.
