### ISSUE TITLE
IPv6 doesn't works by default

### ISSUE THREAD

**Issue by paulcarroty** [maple3142/cf-warp#9]
Interface is up and get address 2a09:bac0::/32, but Linux ignore it and prefer ipv4. 
[More info](https://gist.github.com/oskar456/594f1b5e84ca887c439fb457800b377e#file-wgcf-py-L91)

**Comment by maple3142** [comment]
I don't have ipv6 connection to test, so this needs others to investigate and fix.

**Comment by paulcarroty** [comment]
You don't need to have ipv6, you'll get it from CF.

**Comment by paulcarroty** [comment]
It works. Modify `cf-warp.conf` to

```
Address = 'replace `fd01:5ca1` to `2001:db8` in local ipv6 address, it will be 3rd address'
PostUp = ip6tables -t nat -I POSTROUTING 1 -o %i -j SNAT --to-source ipv6_local_address
PreDown = ip6tables -t nat -D POSTROUTING 1 
```

Tests:

`$ ping -c1 google.com
PING google.com(waw02s14-in-x0e.1e100.net (2a00:1450:401b:805::200e)) 56 data bytes
64 bytes from waw02s14-in-x0e.1e100.net (2a00:1450:401b:805::200e): icmp_seq=1 ttl=58 time=38.3 ms`

```
$ curl -v google.com
*   Trying 2a00:1450:401b:804::200e:80...
* TCP_NODELAY set
* Connected to google.com (2a00:1450:401b:804::200e) port 80 (#0)
> GET / HTTP/1.1
> Host: google.com
> User-Agent: curl/7.68.0
> Accept: */*
> 
```

credits @oskar456

**Comment by maple3142** [comment]
Using that will only work on linux though.

**Comment by paulcarroty** [comment]
Yeah, routing will be different for Windows & MacOS, so platform-specific configs needed.
Also we need more testing on non-Linux OS.

**Comment by maple3142** [comment]
I think the config should be platform-independent. Maybe Wireguard have some config to let you do that easily?
But I am not familiar with Wireguard, so I don't even know it is possible to do that.

**Comment by paulcarroty** [comment]
As much I checked - no. I can write a patch to generate Linux config, or you can add the note to Readme.

**Comment by syphyr** [comment]
You may also want to consider nftables support for ipv6 on linux.

# Nftables rules (disable if iptables is used)
PostUp = nft add table ip6 nat
PostUp = nft add chain ip6 nat prerouting { type nat hook prerouting priority 0\; }
PostUp = nft add chain ip6 nat postrouting { type nat hook postrouting priority 100\; }
PostUp = nft insert rule ip6 nat postrouting oifname %i counter snat to ipv6_local_address
PreDown = nft delete table ip6 nat

**Comment by paulcarroty** [comment]
Doesn't iptables use nftables on backend now?

**Comment by syphyr** [comment]
I believe iptables is currently deprecated and being replaced by nftables in the 5.x kernel.

**Comment by oskar456** [comment]
> It works. Modify `cf-warp.conf` to
> 
> ```
> Address = 'replace `fd01:5ca1` to `2001:db8` in local ipv6 address, it will be 3rd address'
> PostUp = ip6tables -t nat -I POSTROUTING 1 -o %i -j SNAT --to-source ipv6_local_address
> PreDown = ip6tables -t nat -D POSTROUTING 1 
> ```

This is actually an ugly hack - IPv6 NAT in order to get globally routable IPv6 address instead of ULA address. This indeed only works with Linux and iptables. So it's certainly unsafe to put in into default config file (maybe only as a commented-out default)

Instead I hope Cloudflare will eventually change IPv6 prefix to some globally unique address.

> Doesn't iptables use nftables on backend now?

It depends on linux distribution. Classical iptables still work but it is not recommended to combine nftables and iptables rules, although it is technically possible.

**Comment by paulcarroty** [comment]
@oskar456 yeah, it's hack, but I prefer working project with hacks over 50% functionality cut without.

> Instead I hope Cloudflare will eventually change IPv6 prefix to some globally unique address.

I don't see any reason to do it from CF side. Temporary fix is needed anyway.

**Comment by paulcarroty** [comment]
Got it working without NAT&iptables.

**Comment by abbyck** [comment]
> Got it working without NAT&iptables.
@paulcarroty could you explain how?

**Comment by paulcarroty** [comment]
@abbyck when tunnel connects to endpoint the network interface gets ip from `fd01::/16` subnet and Linux ignore it 'cause it's private address. You can fix it by editing precedences in [/etc/gai.conf](https://man7.org/linux/man-pages/man5/gai.conf.5.html):

```
label  ::1/128       0
label  ::/0            1
label  2002::/16     2
label  fd01::/16     1
label ::/96          3
label ::ffff:0:0/96  4
precedence  ::1/128       50
precedence  ::/0          40
precedence  fd01::/16     40
precedence  2002::/16     30
precedence ::/96          20
precedence ::ffff:0:0/96  10
```

**Comment by xqdoo00o** [comment]
A simpler way, just uncomment just one label. for example `label ::1/128       0`,   but uncomment this line `#label fc00::/7      6` not works.

**Comment by ValZapod** [comment]
> interface gets ip from `fd01::/16`

It must get those ips. Those are link-local, ULA addresses.
